# Generated by Django 3.2.8 on 2021-10-11 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='человекочитаемое название', max_length=64)),
                ('key', models.CharField(help_text='ключи являются materialized path и позволяют делать из типов аннотаций иерархичную структуру', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'New'), (10, 'Checked')])),
            ],
        ),
        migrations.CreateModel(
            name='LearnerTextGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='человекочитаемое название жанра', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название школы в которой учится ученик', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО', max_length=128)),
                ('education_level', models.IntegerField(help_text='класс')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_co.school')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerTextAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_offset', models.PositiveSmallIntegerField(help_text='offset начала аннотации')),
                ('end_offset', models.PositiveSmallIntegerField(help_text='offset окончания аннотации')),
                ('correct_text', models.TextField(blank=True, help_text='иcправление аннотации (текст с правильный вариантом. Если в изначальном тексте подстроку [offset_begin:offset_end] заменить на исправление, то должен получиться корректный текст)')),
                ('comment', models.TextField(blank=True, default='')),
                ('annotation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_co.annotationtype')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('learner_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_co.learnertext')),
            ],
        ),
        migrations.AddField(
            model_name='learnertext',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_co.learnertextgenre'),
        ),
    ]
