# Generated by Django 3.2.8 on 2021-10-12 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_co', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerTextScanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='learner_text_scan_page')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school_co.learnertext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
