/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LearnerTextAnnotation { 
    readonly url?: string;
    /**
     * offset начала аннотации
     */
    beginOffset: number;
    /**
     * offset окончания аннотации
     */
    endOffset: number;
    /**
     * иcправление аннотации (текст с правильный вариантом. Если в изначальном тексте подстроку [offset_begin:offset_end] заменить на исправление, то должен получиться корректный текст)
     */
    correctText?: string;
    comment?: string;
    learnerText: string;
    annotationType: string;
    checker: string;
}

